### ISSUE TITLE
Issue with HTTPPOST?

### ISSUE THREAD

**Issue by donnymccoy** [dotarj/PartialResponse#7]
Hi, thanks for making this available!  I'm using this in an HTTPPOST-only API and even though I see the querystring coming in (?fields=x,y,z) for example, the output is not filtered accordingly.  Are there certain return types that are expected?  I'm using ihttpactionresult on my methods.  

I added the lines to global.asax as specified:

`        protected void Application_Start()
        {
            GlobalConfiguration.Configure(WebApiConfig.Register);
            GlobalConfiguration.Configuration.Formatters.Clear();
            GlobalConfiguration.Configuration.Formatters.Add(new PartialJsonMediaTypeFormatter() { IgnoreCase = true });
        }
`

Each method was originally coded to flatten a DTO into JSON as follows:
`return Json(resp)`

where resp is whatever DTO is appropriate for the method.

Can anyone suggest what I am missing?

**Comment by dotarj** [comment]
Hi Danny, the configuration looks good. The problem is that WebApi.PartialResponse only applies the fields parameter in the media formatter, which is bypassed when using JsonResult (more information here: https://docs.microsoft.com/en-us/aspnet/web-api/overview/getting-started-with-aspnet-web-api/action-results).

I've recently released a new version for ASP.NET Core MVC which does support action results, see https://www.nuget.org/packages/PartialResponse.AspNetCore.Mvc.Formatters.Json/ (documentation coming soon). If you have to use ASP.NET Web API you could change the return type of the controller methods to the actual result type, which will enable the media type formatter.

**Comment by donnymccoy** [comment]
Hi, thank you for the quick response!  I believe I tried using a string result type, with no better results.  I'll have to try further because we were using the Json() function to flatten the DTO.  Would I need to bypass that as well?
